#!/usr/bin/env ruby

# Touch some files so they won't be created as root.
system("touch log/development.log")
system("touch log/production.log")
system("touch db/development.sqlite3")
system("touch db/production.sqlite3")
# Install the gem dependencies (if any).
system("sudo rake gems:install")
# Run the main install task.
system("rake install")