#!/usr/bin/env ruby

require 'rubygems'
require 'aws/s3'

# restore_s3_bundle heroku_app_name YYYY-MM-DD
#
unless ENV['AMAZON_ACCESS_KEY_ID'] && ENV['AMAZON_SECRET_ACCESS_KEY']
  raise "you need to set amazon s3 environment variables"
end

AWS::S3::Base.establish_connection!(
  :access_key_id => ENV['AMAZON_ACCESS_KEY_ID'],
  :secret_access_key => ENV['AMAZON_SECRET_ACCESS_KEY']
)

bucket = ARGV[0] + '-backups'
bundle = ARGV[1] + '.tar.gz'

o = AWS::S3::S3Object.find bundle,bucket
puts "Downloading #{bundle} from S3 bucket: #{bucket}..."
File.open(bundle, 'w') do |file|
  file.write o.value
end
